version: "2.0"

services:
  cybert:
    image: img/cybert
    expose:
      - port: 80
        as: 80
        to:
          - global: true

profiles:
  compute:
    tetris:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 1Gi
        storage:
          size: 1Gi
          attributes:
            persistent: true
            class: beta2
          name: data
            size: 5Gi
            attributes:
              persistent: true
              class: beta1
  placement:
    akash:
      pricing:
        tetris:
          denom: uakt
          amount: 100

deployment:
  cybert:
    akash:
      profile: cybert
      count: 1
